### ISSUE TITLE
TCPListener keeps socket open

### ISSUE THREAD

**Issue by SeanFarrow** [cmendible/netDumbster#18]
Hi,

This is a fantastic project, but in my experience, the internal TCPListener is keeping the socket open, making it very diffecult to use from xUnit in a multi-test project.

Therefore I am proposing adding the following line to the server startup:
tcp.Server.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, 1);
this will solve this problem.
Would you like a pull request/is this project maintained anymore?
Cheers
Sean.

**Comment by cmendible** [comment]
Sorry I never got a notification on this issue. I'm planning to move this to dotnetstandard. If you still want to collaborate feel free to send me pull requests.

Cheers,
Carlos

**Comment by cmendible** [comment]
Marking issue as closed since requested change has been merged to master...
