### ISSUE TITLE
TLS Not supported

### ISSUE THREAD

**Issue by adam-drewery** [cmendible/netDumbster#20]
Hi,

Not sure if this is something that can be fixed, but when testing an email sent over TLS i get the error "The SMTP server does not support the STARTTLS extension.".

Thanks,
Adam

**Comment by cmendible** [comment]
Hi,

The feature is not implemented... Do yo want to contribute?

Thanks!

**Comment by gandhibobandhi** [comment]
Hey, I'd love to but unlikely I'll find the time unfortunately. I think I worked around the issue though by changing my client-side connection settings from "Start TLS" to "Start TLS where available". :)

**Comment by cmendible** [comment]
Issue has been stale for 3 years...
