### ISSUE TITLE
HeaderData has ASCII encoding

### ISSUE THREAD

**Issue by Demotron** [cmendible/netDumbster#24]
Hi Carlos!
Thanks for such helpful tool. We use it a lot in our integration tests but I noticed that my tests are failed. I started to look into it and noticed that subject of my mail messages contains characters in UTF-8 encoding (f.e. ’). I saw similar Issue reported for body so it seems the same issue for header data.

**Comment by cmendible** [comment]
Hi @Demotron can you provide more detail or a sample test reproducing the issue?

**Comment by davyfarr** [comment]
Hi @cmendible  I join this thread with a project example, because I think my problem is related to this issue.
I have a unit test with an attachment with UTF8 characters filename that seems to not correctly encode/decode it when the message is received. Hope it helps solve this issue.
[TestSmtpFakeServer.zip](https://github.com/cmendible/netDumbster/files/3212941/TestSmtpFakeServer.zip)
.

**Comment by cmendible** [comment]
Hi @davyfarr thanks for the test. It seems that I´ll have to change MailMessageMimeParser for this. I´ll keep you posted...

**Comment by Demotron** [comment]
Hi Carlos, sorry for delay. I missed the github notification about your message. I hope davyfarr project will help. If not I'll try to bring you example myself too.

**Comment by cmendible** [comment]
Ok guys just updated the [MailMessageMimeParser.cs](https://github.com/cmendible/netDumbster/blob/master/netDumbster/MailMessageMimeParser.cs) with the [MimeKit](https://github.com/jstedfast/MimeKit) implementation. 

I'll try to release version 2.0.05 tomorrow.

**Comment by cmendible** [comment]
Hi guys, just to let you know that I released v [2.0.05](https://www.nuget.org/packages/netDumbster/2.0.0.5). I added @davyfarr test and everything is working as exepected.

@Demotron can you try the version to see if it also fixes your issues?

Thanks!

**Comment by davyfarr** [comment]
Hi @cmendible , I'm sorry to bother you again, but something with the new version messed up my other tests. So the one I sent in the exemple project works as excpected but the other unit tests seems to not correctly decode the body part of the message if there are UTF-8 characters inside.
Now I reverted my nuget pkg to v. 2.0.0.4 and everything is working, except for the UTF-8 characters attachment tests. I'll try to bring you another unit test project as ASAP.
Thanks for now! I really appreciate your work and your effort.

**Comment by cmendible** [comment]
Hi @davyfarr I also had issues with the Russian text test, and had to modify the validations cause now the parser does the heavy lifting for us.

Check line 147 of **TestBase.cs** in the following [diff](https://github.com/cmendible/netDumbster/commit/f08037ea09eb0cc31c77551bd8275b62da8d4871#diff-b662ce4023c4627999601aa53d147474)

**Comment by cmendible** [comment]
Just added this test: d557c1ed99aaa4c9a5647f8615b40ce4d33607db hope it helps!
