### ISSUE TITLE
FileLoadException: something about MimeKit not being loaded

### ISSUE THREAD

**Issue by jacargentina** [cmendible/netDumbster#25]
No se puede cargar el archivo o ensamblado 'MimeKit, Version=2.1.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' 

In Spanish exception; I don't know why? I must mention I' already using MailKit and MimeKit on my project.

**Comment by jacargentina** [comment]
I have MimeMit 2.2.0.0

**Comment by cmendible** [comment]
I see.... Can you try adding a binding redirect in your configuration? I'll try to update the lib during next weekend.

**Comment by jacargentina** [comment]
@cmendible also I should note:  Exception on client side is ` The SMTP server has unexpectedly disconnected.` (in my case I'm using MailKit); would be nice to have some mechanism on nDumbster itself to know the **"server side Exception"**

**Comment by cmendible** [comment]
In this case netDumbster assembly is not loading and therefore there is no way to send a better message to the client. Did you try the binding redirect approach?

**Comment by jacargentina** [comment]
@cmendible sorry i've not make it very clear: yes, the binding redirect is done and working just fine.

The other obscure exception (that i detected by cloning the repo and referencing on VS and debugging....) is that `Subject` seems a required header for MimeKit.

That other exception is the one very obscure.

**Comment by jacargentina** [comment]
@cmendible  any change to update MimeKit to latest ?

**Comment by cmendible** [comment]
With PR #27 MimeKit was updated to 2.5.1. I've not published a new nuget package yet. Please let me know if it works for you

**Comment by jacargentina** [comment]
Yes! I've redirected to 2.5.1 and it works just fine.

**Comment by jacargentina** [comment]
Oh! BTW, i've just found i also need the #27 PR because of the missing 2 characters on Body

**Comment by cmendible** [comment]
@jacargentina v 2.0.0.6 has been released: https://www.nuget.org/packages/netDumbster/2.0.0.6 

Hope it helps!

**Comment by jacargentina** [comment]
@cmendible MimeKit was not updated   😉

**Comment by cmendible** [comment]
My mistake... Please reopen the issue...

**Comment by jacargentina** [comment]
[I can't](https://stackoverflow.com/a/21333938/2917185)

- you **cannot** re-open your own issues if a repo collaborator closed them

**Comment by cmendible** [comment]
@jacargentina just released https://www.nuget.org/packages/netDumbster/2.0.0.7
