### ISSUE TITLE
Body is "cut" when using Mimekit/MailKit

### ISSUE THREAD

**Issue by joaopgrassi** [cmendible/netDumbster#26]
I'm using MailKit + Mimekit to send emails in my .net app, since the one from `System.Net.Mail` is obsolete (https://github.com/dotnet/dotnet-api-docs/issues/2986) and decided to give this a go for my unit tests.
 
After setting up the tests, they failed when asserting the body message. Somehow when getting the body via `MessageParts[0].BodyData` returns always the original message without the last two characters. 

Here's an example test using MailKit (need to add the NuGet package to the test project)

```
[Fact]
public async Task Send_MimeKitEmail()
{
    using (var client = new MailKit.Net.Smtp.SmtpClient())
    {
        client.ServerCertificateValidationCallback = (_, __, ___, ____) => true;
        
        await client.ConnectAsync("localhost", this.server.Configuration.Port, false).ConfigureAwait(false);
        client.AuthenticationMechanisms.Remove("XOAUTH2");
        
        var from = new MimeKit.MailboxAddress("carlos@mendible.com");
        var to = new MimeKit.MailboxAddress("karina@mendible.com");
        var body = "this is the body";
        
        var message = new MimeKit.MimeMessage();
        
        message.From.Add(from);
        message.To.Add(to);
        message.Subject = "test";
        message.Body = new MimeKit.TextPart("plain") { Text = body };
        
        client.Send(message);
    }
    
    Assert.Equal(1, server.ReceivedEmailCount);
    // this fails with the BodyData returning: "this is the bo"
    Assert.Equal("this is the body", server.ReceivedEmail[0].MessageParts[0].BodyData);
}
```

Not sure if am I missing something obvious or if this is a bug.

**Comment by joaopgrassi** [comment]
Okay so ran the test and debugging, it seems I confirmed my suspicions: `SmtpMessage` on line `30`:
```
rawMessage = rawMessage.Substring(0, rawMessage.Length - 4);
```
If I'm not mistaken this is to remove the carriage return from the raw message, so the body can be "extracted".
Instead, why not just do: `rawMessage.TrimEnd()` or `rawMessage.TrimEnd('\r', '\n');`? Should be safer I guess. Did here and all tests seem to pass.

**Comment by cmendible** [comment]
I will go for the second option. Can you make a PR  with the code change and the test that proves your issue gets fixed?

**Comment by joaopgrassi** [comment]
Sure! I'll send it over later today.
