### ISSUE TITLE
Some tests fail when running in unix environments

### ISSUE THREAD

**Issue by joaopgrassi** [cmendible/netDumbster#28]
~~Following #27 it would be nice to have multi-platform builds. We can do so in Azure Pipelines: [Create a multi-platform pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops)~~

Re-pourpusing this in order to investigate why the test `If_Client_Is_Not_Disposed_Server_Keeps_Working` (socket exception) fails when running on unix machines.

**Comment by cmendible** [comment]
Thanks to https://github.com/cmendible/netDumbster/issues/31#issuecomment-764862367 replacing the use of port 25 in the tests fixed this issue!

**Comment by cmendible** [comment]
Closed vía #32
