### ISSUE TITLE
Reusing SmtpClient hangs in net50

### ISSUE THREAD

**Issue by chrisaut** [cmendible/netDumbster#30]
The following test succeeds when running under netcoreapp3.1, but fails by timing out in net50

```C#
[Fact(Timeout = 10000)]
public async Task Net50Repo()
{
    var config = Configuration.Configure();
    using var server = SimpleSmtpServer.Start(config.WithRandomPort().Port);
    var inst = new SmtpClient
    {
        Host = "localhost",
        Port = server.Configuration.Port,
        EnableSsl = false
    };

    for (int messageNo = 0; messageNo < 2; messageNo++)
    {
        var mailMessage = new MailMessage("one@example.com", "two@example.com");

        await inst.SendMailAsync(mailMessage);

        Assert.Equal(messageNo + 1, server.ReceivedEmailCount);
    }
}
```

The issue seems to be reusing the SmtpClient, the first SendMailAsync succeeds, but the second call always just hangs indefinitely.

Works in 3.1. Newing up a new client for each call also works. Testing against a different Smtp server (eg. Papercut) also works.

netDumpster just ends up waiting inside SmtpContext on this line:
```C#
count = this.socket.Receive(byteBuffer);
```

It's like if the socket remains open it cannot be reused anymore for some reason. Any idea what changed?

**Comment by cmendible** [comment]
@chrisaut I just added your test to the project:

https://github.com/cmendible/netDumbster/blob/edabbce7be4cf2cc02e2dce5efd2e6b733b5aa2b/netDumbster.Test/TestsBase.cs#L319

My findings so far are that for .NET 5 it fails only if using the `SendMailAsync` method of the `SmtpClient`.

**Comment by chrisaut** [comment]
Thanks for taking a look.

BTW I forgot to mention that adding `.ConfigureAwait(false)` also does not help.

**Comment by cmendible** [comment]
I created a branch to try to fix this issue.: https://github.com/cmendible/netDumbster/tree/dotnet5

**Comment by scalablecory** [comment]
Is your server on 127.0.0.1?

Default on many OS is to try IPv6 first, and that may take time to fail.

**Comment by cmendible** [comment]
It should be listening by default in all network interfaces: 

https://github.com/cmendible/netDumbster/blob/bd16f481cf6b0b37019d5c59e32e01f11c123779/netDumbster/Configure.cs#L17

The test only fails on .NET 5 if using the SendMailAsync method of the SmtpClient. If you rerplace the calll with SendMail or execute the same code on .NET Core 3.1.x everything runs as expected.

**Comment by scalablecory** [comment]
IPAddress.Any will bind on IPv4, so you'll see the same issue.

Consider binding to IPAddress.IPv6Any and setting DualMode=true to listen on both v4 and v6.

**Comment by cmendible** [comment]
I'll try that and come back with the results...

**Comment by cmendible** [comment]
@scalablecory listening on IPAddress.IPv6Any has no effect and setting DualMode results in a bunch of `System.NotSupportedException : This protocol version is not supported`

Wouldn't the behavior that you describe affect all tests and not just the ones the reuse the SmtpClient?

**Comment by chrisaut** [comment]
There seem to be [other issues](https://github.com/dotnet/runtime/issues/46953) with SmtpClient in 5.0 too. They even go so far as to say they recommend migrating to MailKit

Still, perhaps we should raise the issue over at the runtime repo? This is, after all, a clear regression and we do have a nice repo test.

Or have you found out what the issue is yet?

**Comment by cmendible** [comment]
Nope I have not find anything else but I will try the **MailKit** approach just to check if the culprit is the client and not the **netDumbster** implementation.

Once I get the results we'll know for sure if it's related or not to the SmtpClient.

**Comment by cmendible** [comment]
@chrisaut using **MailKit** fixes the issue. You can check the following branch: https://github.com/cmendible/netDumbster/tree/dotnet5-mimekit and job results: https://github.com/cmendible/netDumbster/actions/runs/633588531

There is definitely something wrong with **SmtpClient ** in .NET 5

**Comment by cmendible** [comment]
Since 443befae2113d6bec0cfde552ebdc5fa88815705 test project targets .NET 5 and use **MailKit** to send emails avoiding the issue with the native **SmtpClient**.

**Comment by chrisaut** [comment]
As you can see I've opened an issue on the runtime repo, I still hope this is a bug that can be fixed in a service release.

If it is, I recommend netDumbster add at least a couple of tests back using SmtpClient, as that still is the std. and as a unit testing lib it would be nice to support. 

Thanks for your help looking into this.
