### ISSUE TITLE
c# - how to get email Subject?

### ISSUE THREAD

**Issue by jimmycr** [cmendible/netDumbster#33]
Hello community, I'm probably dumb. I'm trying to receive email using netDumbster. I'm able to get email body, but how to get email Subject? Thanks for help!

        static void Main()
        {
            SimpleSmtpServer server = SimpleSmtpServer.Start(25);
            while (true)
            {
                if (server.ReceivedEmailCount > 0)
                {
                    foreach (SmtpMessage message in server.ReceivedEmail)
                    {
                        Console.WriteLine("----------------------------------------------------------------");
                        Console.WriteLine(message.ToAddresses[0].ToString());  //first ToAddress
                        //how to print message SUBJECT???
                        Console.WriteLine(message.MessageParts[0].BodyData.ToString());   //email body
                    }
                server.ClearReceivedEmail();
                }
                Thread.Sleep(100);
            }
        }

**Comment by jimmycr** [comment]
I probably got it. I had to download project and change file **SmtpMessage.cs** - append:
------------------------------------------------------------------
        public string Subject
        {
            get
            {
                if (this.Headers.AllKeys.Select(k => k.ToLowerInvariant()).Contains("subject"))
                {
                    return this.Headers["subject"].ToString();
                }
                else
                {
                    return string.Empty;
                }
            }
        }
------------------------------------------------------------------

Seems to work - am I right? I thought I use nuGet to get this to VisualStudio and everything will work :) . I was really surprised, that message subject is not present :)

**Comment by cmendible** [comment]
Wow! the Subject property has been missing for ages!😋

I just added the missing code: b09977c19debcc555995edf2b171074ed5a4855d and a test: 24797bef9cf021950b7de4db9bda19b6b0912ca0

**Comment by cmendible** [comment]
Subject property is available in v.2.0.0.8

**Comment by jimmycr** [comment]
Thanks!!
