### ISSUE TITLE
The SMTP server does not support authentication

### ISSUE THREAD

**Issue by kadyrkulovr** [cmendible/netDumbster#35]
Hi,

When I try to use method _Authenticate_ I get the following error message:

> System.NotSupportedException: 'The SMTP server does not support authentication.'

`client.Authenticate("userName", "Password");`

Could you suggest how to fix this error? I saw in your test project that you use SmtpClient with authentication.

![image](https://user-images.githubusercontent.com/6756259/149497293-1ffb49ec-b911-40da-8004-ccbec40ff186.png)

![image](https://user-images.githubusercontent.com/6756259/149498589-ccfef288-bcad-4395-8df9-16e056c63227.png)

**Comment by DRESAAN** [comment]
Hi, I had the same problem and after a few hours of analysing I realised that the changes, that enable the authenication are newer than the NuGet 2.0.0.8. So the authentication feature has just not been released.

You can clone the repository and build it on your own or wait for the next NuGet release. Maybe @cmendible will release it in the near future? :)

**Comment by cmendible** [comment]
@kadyrkulovr @DRESAAN thanks for reporting this. Please upgrade to version 3.0.0: https://www.nuget.org/packages/netDumbster/3.0.0 and let me know if it works for you.
